version: 2.1
executors:
  default:
    docker:
      - image: hashicorp/terraform:light
commands:
  initialize:
    steps:
      - run: sh .circleci/create_credential.sh .terraformrc
      - run: terraform init
jobs:
  build:
    executor: default
    steps:
      - checkout
      - initialize
      - run:
        name: Validate terraform
        command: terraform validate
      - run:
        name: Plan terraform
        command: terraform plan
  deploy:
    executor: default
    steps:
      - checkout
      - initialize
      - run:
        name: Apply terraform
        command: terraform apply -auto-approve
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold:
        type: approval
        requires:
          - build
      - deploy:
        requires:
          - hold
